### ISSUE TITLE
Enhancement request for new issue templates and additional tasks

### ISSUE THREAD

**Issue by User-green** [tenacityteam/tenacity-legacy#32] opened 2021-07-05 21:36 UTC
I would suggest considering:
- Adding following issue templets:
-- Question — there is a LOT of them now
-- Meta-request — something, not related to codebase, but to legal (like tredemark, ilcense, etc), community (chats, new contributors, etc), github (like this suggestion).
-- Other — templet for thing, that does not fit into any other templet
- Adding tasks:
-- Auto-assign lables via "Actions"
-- Auto-bumping versions via "Actions"
- Updating `PULL_REQUEST_TEMPLATE.md`, `CONTRIBUTEING.md` to mach current state of things. 

UPDATE:
- Creating "Experemantal" branch

**Comment by JakoonStick** [comment] 2021-07-05 21:54
https://github.com/SartoxOnlyGNU/audacium. I think both projects should merge as both are devs and can contribute to eachother.

**Comment by emabrey** [comment] 2021-07-06 03:10
> 
> 
> https://github.com/SartoxOnlyGNU/audacium. I think both projects should merge as both are devs and can contribute to eachother.

The logo they are using is an overt trademark violation unfortunately. Also, they have a right to make their own fork that is separate from ours. It looks like they have 3-5 contributors right now and I didn't see you, @JakoonStick , as one of them, so unless I'm mistaken there is not a reason to believe they even want to combine the forks. This isn't really a bug, so I am going to mark it as an enhancement request. Please make separate issues for each individual request in the future. 

The chatroom request is a duplicate, and should be discussed at issue #7.
I believe the enhancement request for replacing offending links is a duplicate of #4.
Please elaborate what "to ma[t]ch current state of things" means with regard to the two markdown files.

**Comment by User-green** [comment] 2021-07-06 17:34
> The chatroom request is a duplicate, and should be discussed at issue #7.

I know, so I linked it. But you are right. I shuld not done this. 

> I believe the enhancement request for replacing offending links is a duplicate of #4.

Yep, you right.

> Please elaborate what "to ma[t]ch current state of things" means with regard to the two markdown files.

Both of this files describes old (main branch) standarts. However, we are not the main branch, so, I think this files should bu updated.

**Comment by Be-ing** [comment] 2021-08-19 20:37
I don't really understand what this issue is about?

**Closed as completed by Be-ing** 2021-08-19 20:37 UTC
Labels: enhancement
