### ISSUE TITLE
[Request] Please read comment before removing thanks! App Name To Be CleanCity

### ISSUE THREAD

**Issue by JadenJSJ** [tenacityteam/tenacity-legacy#76] opened 2021-07-06 15:21 UTC
**Is your feature request related to a problem?** No

**Describe the solution you'd like**
The app name should probably be **CleanCity**
I mean its clean from all the telemetry & spyware right?

Sorry the name vote post was locked and I really wanted this to be in there :/

**Comment by JPcode05** [comment] 2021-07-06 16:03
@JadenJSJ CleanCity is not a good name for an audio editor. Sorry, but at least we read the comment.

P.S. Nice profile picture!

**Comment by EricBright** [comment] 2021-07-06 17:27
Closed as duplicate of #33.

**Closed as completed by EricBright** 2021-07-06 17:27 UTC
Labels: duplicate
