### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by eduardomunhozr** [tenacityteam/tenacity-legacy#623] opened 2021-09-14 21:14 UTC
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

Audacity-2.4.1-1947-gdce03ba

### Describe the bug.

if you look at the device selection you'll notice it looks weird, even when selected they're still blank, plus their size is not well divided (selection of channels is partially covered by the other options)

![image](https://user-images.githubusercontent.com/76234597/133334416-6e6fb759-de4e-4ae7-bfa3-d21252f6d954.png)

### Expected behavior

it should show which devices are selected and widgets should be better separated from each other

### OS

Zorin OS 16

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by fitojb** [comment] 2021-09-14 23:12
Duplicate of #435

**Closed as completed** 2021-09-15 05:32 UTC
Labels: bug, duplicate
